services:
  arangodb:
    image: arangodb:3.11
    container_name: arangodb
    ports:
      - "8529:8529"
    env_file:
      - .env
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD}
    volumes:
      - ./docker-data/arangodb:/var/lib/arangodb3
    restart: unless-stopped
